### ISSUE TITLE
Resume Suggestions

### ISSUE THREAD

**Issue by Nlorenc2760** [CSC510-Do-Lorenc-McDavitt/jobtrackr#4]
Provide suggestions for resume improvement using Ollama.

Context Provided to Ollama: Resume (obviously) and the job description to tailor the resume towards.

These suggestions should be displayed to the user on a new page, which should be accessible from the top bar. The page will have the resume on the left and the suggestions on the right.

For the implementation side, the file on the left could be a preview of a resume that is stored in S3. On the right, the suggestions should be displayed in text form as a large paragraph of information. The input for the resume and job description will be in the form of text and be up to the user to copy and insert.

**Comment by Kethly** [comment]
It seems like the resume improvement using Ollama can be done pretty simply by using the previous template for generating a cover letter.

**Comment by jfmcdavitt** [comment]
Front End Page built and merged in with #13. Now need to create Prompt Engineering test cases for it then this will be complete
