### ISSUE TITLE
Refactor Landing Page

### ISSUE THREAD

**Issue by Nlorenc2760** [CSC510-Do-Lorenc-McDavitt/jobtrackr#5]
Currently, the kanban board requires the user to change the property of each application by clicking on the application and changing the status.

This should be improved by allowing the user to drag and drop the applications between the various states of the application process for improved usability.

**Comment by jfmcdavitt** [comment]
From what I've discovered the original board that was created by drawing columns and then drawing the cards into their appropriate columns. Problem with that implementation is it doesn't allow us to dynamically move the cards around. So I'm going to have to create a new component and work it into the existing system

**Comment by jfmcdavitt** [comment]
Going to put a pin in this to work on the Resume Suggestions portion of the project

**Comment by jfmcdavitt** [comment]
It is unlikely we would be able to complete this before the due date. So for this one we are going to pivot to a dropdown menu at the bottom of each of the cards to allow them to be moved more quickly

**Comment by jfmcdavitt** [comment]
Right now the Landing Page is a hot mess to modify, so I'm going to take the work I did for drag and drop to componentize it to make it easier to work with and add some small quality of life updates such as a drop down menu to make it easier to move between files
